### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by viebel** [darky/node-remote-repl#1]
I could not understand from the README how to use node-remote-repl.

How many processes should run? What should be the content of `repl.js`? Should there be another node process running?

Could you give a full example with full details?

**Comment by darky** [comment]
> Should there be another node process running?

Yes, **node-remote-repl** is simple command line tool, that execute your code on remote process via inspect protocol (same protocol, which used by IDE for debugging)
https://nodejs.org/dist/latest-v16.x/docs/api/cli.html#cli_inspect_host_port

> How many processes should run?

At least one process. Need to run nodejs process with `--inspect` flag and then you can connect to this process with **node-remote-repl** and execute some code

> What should be the content of repl.js?

https://github.com/darky/node-remote-repl#some-use-cases

**Comment by viebel** [comment]
Thank you for the clarification.

**Comment by darky** [comment]
@viebel maybe will be interesting for you
New project here https://github.com/darky/repl-ns
**repl-ns** + **node-remote-repl** allow to feel Clojure like REPL driven development experience on Node.js
